[supervisord]
nodaemon=true
logfile=/workspaces/%(ENV_REPO_NAME)s/automation-os/logs/supervisord.log
pidfile=/workspaces/%(ENV_REPO_NAME)s/automation-os/logs/supervisord.pid
loglevel=info

[program:dashboard]
command=python3 /workspaces/%(ENV_REPO_NAME)s/automation-os/dashboard/app.py
autorestart=true
startretries=5
stdout_logfile=/workspaces/%(ENV_REPO_NAME)s/automation-os/logs/dashboard.out.log
stderr_logfile=/workspaces/%(ENV_REPO_NAME)s/automation-os/logs/dashboard.err.log
environment=PYTHONPATH="/workspaces/%(ENV_REPO_NAME)s/automation-os"

[program:worker_os]
command=python3 /workspaces/%(ENV_REPO_NAME)s/automation-os/schedulers/master_run.py
autorestart=true
startretries=5
stdout_logfile=/workspaces/%(ENV_REPO_NAME)s/automation-os/logs/worker_os.out.log
stderr_logfile=/workspaces/%(ENV_REPO_NAME)s/automation-os/logs/worker_os.err.log
environment=PYTHONPATH="/workspaces/%(ENV_REPO_NAME)s/automation-os"
